version: '3'
services:

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - local
    ports: 
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  mongo-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    volumes:
      - ./mongodb/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-db-data:/data/db
    networks:
      - local
  
  iot-console1:
    build: ./
    mem_limit: 512m
    mem_reservation: 256M
    cpus: 0.25
    scale: 1
    ports:
      - 8050:8050
    networks:
      - local
    depends_on:
      - postgres-db
      - mongo-db

  iot-console2:
    build: ./
    mem_limit: 512m
    mem_reservation: 256M
    cpus: 0.25
    scale: 1
    ports:
      - 8051:8050
    networks:
      - local
    depends_on:
      - postgres-db
      - mongo-db

  local-nginx:
    build: ./nginx
    ports:
      - 8888:80
    networks:
      - local
    depends_on:
      - iot-console1
      - iot-console2

volumes:
  db-data:
  mongo-db-data:

networks:
  local:
    name: local