apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-console
spec:
  selector:
    matchLabels:
      app: iot-console
  replicas: 1
  template:  
    metadata:
      labels:
        app: iot-console        
    spec:
      containers:     
      - image: iot-console:latest
        name: mongodb       
        ports:
        - containerPort: 8050      
        imagePullPolicy: Never
        resources:
          limits:
            memory: "520Mi"
            cpu: "0.3"
          requests:
            cpu: "0"
            memory: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: iot-console
  labels:
    app: iot-console
spec:
  ports:
    - port: 8050
  type: LoadBalancer  
  selector:
    app: iot-console